### ISSUE TITLE
After run perftool.py in Rhel8.1 with Avocado(version:77.0), it shows "CANCEL: gcc-g++ is needed for the test to be run", which makes the result FAIL

### ISSUE THREAD

**Issue by Gene-Lo** [deater/perf_event_tests#20]
【Test Result】
After run perftool.py in Rhel8.1 with Avocado(version:77.0), it shows "CANCEL: gcc-g++ is needed for the test to be run", which makes the result FAIL. SOL-log is like below:

(1/1) perftool.py:Perftool.test: CANCEL: gcc-g++ is needed for the test to be run (9.69 s)
RESULTS : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1

However, we can't install "gcc-g++" in Rhel8.1 so far. Please check if Rhel8.1 supports "gcc-g++" and the test of perftool.py.

【Expect Result】
After run perftool.py, it should show PASS.

【Test Steps】
Run perftool.py via cmd "avocado run perftool.py"

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.5.1.el8_1.ppc64le

[FW configuration]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod

[HW configuration]
CPU DD2.3 20core *2
Hynix (HMA82GR7CJR4N-VKT3/F) 16G *32
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *2

【Test log】
[Test.log.zip](https://github.com/deater/perf_event_tests/files/4543158/Test.log.zip)

**Comment by deater** [comment]
I think you have the wrong package here, this is perf_event_tests not perftool-testsuite
